print(f"Your story begins in your small bedroom.\n"
    "Before anything else, you must decide who you are.\n"
    "Choose your first name, last name, and your starting traits:\n"
    "Bravery, Intelligence, Loyalty, or Cunning.\n"
    "These choices will shape your adventure.\n\n"
    "Suddenly, you hear a noise at the window.\n"
    "*TAP! TAP! TAP!*\n"
    "An owl flies through the window, delivering a letter sealed with the\n\n"
    "Dear Student,\n"
    "We are pleased to inform you that you have been accepted to Hogwarts\n"
    "School of Witchcraft and Wizardry!\n"
    "Do you accept this invitation and go to Hogwarts?\n"
    "1. Yes, of course!\n"
    "2. No, I'd rather stay with Uncle Vernon...\n"
    "Your choice:"
    "You tear up the letter, and Uncle Vernon cheers:\n""
    "“EXCELLENT! Finally, someone NORMAL in this house!”\n""
    "The magical world will never know you existed... Game over."
    "An owl lands on the sill and drops a letter with your name on it:\n"
    f"{first_name} {last_name}.\n"
    "Inside, you discover something incredible:\n"
    "You have been accepted to Hogwarts School of Witchcraft and Wizardry.\n\n"
    "A few moments later, someone knocks loudly at your door.\n"
    "*BOOM! BOOM! BOOM!*\n"
    "You open it and see a giant man with a big beard.\n"
    "\"Hello there! I'm Hagrid,\" he says. \"I'm here to take yeh to buy your school supplies.\"\n\n"

      "You follow him into a hidden magical street full of shops: Diagon Alley.\n"
      "You check your money:\n"
      f"Gold: {gold} | Silver: {silver} | Bronze: {bronze}\n"
      "You will need to buy your wand, robes, a cauldron, and basic supplies.\n"
      "Choose wisely—your adventure at Hogwarts is about to begin!")
